[package]
name = "esp-idf-sys"
version = "0.19.6"
authors = ["Alexey Arbuzov <aarbuzov@termt.com>", "sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["sys", "idf", "esp-idf", "esp32"]
description = "Bindings for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
license = "MIT OR Apache-2.0"
readme = "README.md"
links = "esp_idf"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std", "pio"]

std = ["embedded-svc/std"]

# Use `platformio` to build the `esp-idf`
pio = []
# Experimental: Use native `esp-idf` tooling to build it
native = ["strum"]

[dependencies]
mutex-trait = "0.2"
embedded-svc = "0.8.3"
paste = "1"

[build-dependencies]
embuild = "0.23.5"
anyhow = { version = "1" }
strum = { version = "0.21", optional = true, features = ["derive"] }
